### ISSUE TITLE
BE-Docs. Todo

### ISSUE THREAD

**Issue by jihwankim128** [jihwan1535/techblog#36]
- [ ] Controller Validation 추가
- [ ] 멤버 객체 Auth 도메인으로 분리
- [ ] Global Exception Handler 적용
- [ ] Repository JPA 적용
- [ ] Service 추상화
- [x] #81
- [ ] Controller 리플렉션 적용
- [ ] ETC
